# Generated by Django 4.2.4 on 2023-08-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
