# Generated by Django 4.2.4 on 2023-08-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
